export const bridgeConfig = {
  ANDROID_INTERFACE_KEY: "__BRIDGE_INTERFACE_FOR_ANDROID__", // android接口对象key
  WEB_INTERFACE_KEY: "__BRIDGE_INTERFACE_FOR_WEB__", // web接口对象key

  RESOLVE_CALLBACK_KEY: Symbol("RESOLVE_CALLBACK_KEY"), // 成功回调key
  REJECT_CALLBACK_KEY: Symbol("REJECT_CALLBACK_KEY"), // 失败回调key

  GLOBAL_EVENT_CHANNEL_ID: "__GLOBAL_EVENT_CHANNEL__" // 全局事件通道id
};
